print("meu nome é Bhernardo Ramos Vieira")
print("tenho 21 anos")
print("peso 80kg")
print("a primeira vez que fiz isso estava na primeira fase")
print("Atualemnte estou na 4 fase de Analise e Desenvolvimento de Sistemas")
